CREATE TABLE stats
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count                BIGINT,
    count_by_pressure    BIGINT,
    count_by_voltage     BIGINT,
    count_by_humidity    BIGINT,
    count_by_temperature BIGINT,
    download_date        date,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);