
spring:
  application:
    name: stats
  datasource:
    password: 'suneclipse'
    driver-class-name: org.postgresql.Driver
    username: suneclipse
    url: jdbc:postgresql://localhost:5433/statstest
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
springdoc:
  show-login-endpoint: true

logging:
  level:
    org:
      flywaydb: DEBUG
server:
  port: 8081