ALTER TABLE sensors
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE sensors
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE sensors
    ALTER COLUMN type TYPE VARCHAR(255) USING (type::VARCHAR(255));

ALTER TABLE sensors
    ALTER COLUMN unit TYPE VARCHAR(255) USING (unit::VARCHAR(255));